import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CutiGo",
  description: "Generated by create next app",
  icons: {
    icon: '/cutigo-logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
    </>
  );
}
